---
env:
  node: true
  es2022: true
extends:
  - airbnb
parserOptions:
  ecmaVersion: 2022
rules:
  indent: ["warn", 2]
  max-len: ["warn", 100]
  no-undef: "error"
  no-unused-vars: ["error", {"varsIgnorePattern": "^_"}]
  no-use-before-define: 0
  operator-linebreak: 0
  require-jsdoc: 0
  semi: 0

settings:
  react:
    version: 999.999.999
