---
env:
  node: true
  es2022: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2022
rules:
  indent: [warn, 2]
  max-len: [warn, 100]
  no-use-before-define: 0
  operator-linebreak: 0
  semi: 0

settings:
  react:
    version: 999.999.999
