---
env:
  node: true
  es2021: true
extends:
  - airbnb
parserOptions:
  ecmaVersion: 12
rules: {
  indent: ["warn", 2],
  max-len: ["warn", 100],
  no-console: 0,
  no-undef: "error",
  no-unused-vars: ["error", {"varsIgnorePattern": "^_"}],
  no-use-before-define: 0,
  operator-linebreak: 0,
  require-jsdoc: 0,
  semi: 0
}
