---
name: Setup Erlang/OTP with optional Elixir (and mix) and/or rebar3
description: >
  Set up a specific version of Erlang/OTP, Elixir, and/or rebar3
  and add the command-line tools to the PATH
author: Erlang Ecosystem Foundation
branding:
  color: blue
  icon: code
inputs:
  otp-version:
    description: Version range or exact version of Erlang/OTP to use,
      or false when installing only Gleam without OTP
    required: true
  elixir-version:
    description: Version range or exact version of Elixir to use
  gleam-version:
    description: Version range or exact version of Gleam to use
  install-hex:
    description: Whether to install Hex (with mix local.hex
      when installing Elixir)
    default: true
  install-rebar:
    description: Whether to install Rebar (with mix local.rebar
      when installing Elixir)
    default: true
  rebar3-version:
    description: Version range or exact version of rebar3 to use (or nightly)
  version-type:
    description: strict means the versions are take as-are; loose means we try
      to guess versions based on semver rules
    default: loose
  disable_problem_matchers:
    description: whether to have the problem matchers present in the results
      (or not)
    default: false
  version-file:
    description: a versions file (e.g. as used by `asdf`), which defines inputs
    default: ''
outputs:
  elixir-version:
    description: Exact version of Elixir that was installed
  otp-version:
    description: Exact version of Erlang/OTP that was installed
  gleam-version:
    description: Exact version of Gleam that was installed
  rebar3-version:
    description: Exact version of rebar3 that was installed
runs:
  using: node16
  main: dist/index.js
