name: Setup Elixir
description: Set up a specific version of OTP and Elixir and add the command-line tools to the PATH
author: GitHub
branding:
  color: blue
  icon: code
inputs:
  elixir-version:
    description: Version range or exact version of Elixir to use
  otp-version:
    description: Version range or exact version of OTP to use
  experimental-otp:
    description: Whether to use experimental builds of OTP (images that have not yet been fully tested include ubuntu-16.04, ubuntu-18.04, ubuntu-20.04)
    default: false
  install-hex:
    description: Whether to install Hex
    default: true
  install-rebar:
    description: Whether to install Rebar
    default: true
outputs:
  elixir-version:
    description: Exact version of Elixir that was installed
  otp-version:
    description: Exact version of OTP that was installed
runs:
  using: node12
  main: dist/index.js
