name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "23.2"
          gleam-version: "0.19.0-rc3"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
