#!/bin/bash

set -eo pipefail

wget -q https://repo.hex.pm/builds/elixir/v${1}-otp-${2}.zip
unzip -d .setup-elixir/elixir v${1}-otp-${2}.zip
rm v${1}-otp-${2}.zip
echo "::add-path::$(pwd)/.setup-elixir/elixir/bin"
