#!/bin/bash

set -eo pipefail

release=$(lsb_release -cs)
version=$1
file=esl-erlang_$version-1~ubuntu~$release\_amd64.deb

sudo apt-get install -y libwxbase3.0-0v5
sudo apt-get install -y libwxgtk3.0-0v5
sudo apt-get install -y libsctp1

cd /tmp

wget https://packages.erlang-solutions.com/erlang/debian/pool/$file
sudo dpkg -i $file