#!/bin/bash

set -eo pipefail

release=$(cat /etc/os-release | grep UBUNTU_CODENAME | cut -d= -f2)
version=$1
arch=$2
file=elixir_$version-1~ubuntu~$release\_$arch.deb

cd /tmp

wget https://packages.erlang-solutions.com/erlang/debian/pool/$file
sudo dpkg -i $file